### PR TITLE
Add monostock

### LINKED ISSUE #4: Dagster "monostock"?
Thanks for getting this one going!

Mentioned over on https://github.com/conda-forge/dagster_graphql-feedstock/pull/2

> Also, while looking over the repos, it looks like dag(ster|git)* are simultaneously released with the same version. Perhaps it makes sense to:
>
>-    move them all into one feedtock (dagster?)
> -    keep triggering the bot off the main dagster pypi tarball, as they make tags-per-push
> -   do all the builds from source.
>
> It's a big source tarball (they check in their yarn packages) but it should be much easier to keep everything consistent.

Right now, I'm just seeing what i can do with dagster, and not looking for _another_ ecosystem to be on the hook to maintain, but would be interested in exploring at least getting to the above... if it _did_ work, it should be much easier to maintain.

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

- fixes #4 (if that's what we want)
- renames all of the packages to be hyphenated, rather than snake case
- adds `pip check` everywhere it can, lead to some version tweaks

This is gnarly, but works. It could be the better approach would be to have `dagster` (the only non-`noarch` package) be standalone (so decline this PR), and have a `dagster-libraries` or something that's purely `noarch`, as it does take _a while_. But won't know if we don't try!

### CODE REVIEW

**Comment by bollwyvl** [comment]
going to let these ride before fixing the linter stuff...

**Comment by bollwyvl** [comment]
I'm frankly surprised at that level of success! 

So it looks like _at least_ `aws` can't actually be `noarch` because of cute emoji in the terminal... and it could be the `slack` stack needs some archaelogical pins (or can't be `pip check`ed, which scares me now that I know it exists).

**Comment by xhochy** [comment]
Depends on https://github.com/conda-forge/watchdog-feedstock/pull/14

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

Well, adding `dagstermill` might fail somehwere out in the matrix, but otherwise this is as far as i can take the concept at this point.

Of the remaining six packages:
```
# - dagster-airflow  issues with python 3.8
# - dagster-aws      issues with python 3.8
# - dagster-celery   missing transient dependency (billiard >=3.6.1)
# - dagster-dask     issues with python 2.7
# - dagster-gcp      issues with win/python 2.7
# - dagster-pyspark  issues with python 3.8
```
The celery and gcp stuff should clear up. Of the remaining, aws has a dependency on pyspark, so the PRs would still be a _little_ involved to order properly, but on the whole this seems pretty effective.

**Comment by bollwyvl** [comment]
alas, it appears the required version of papermill also doesn't work with py27.

**Comment by xhochy** [comment]
Feel free to merge, I can also archive the feedstocks we then no longer need.

**Comment by bollwyvl** [comment]
I'll be away from keyboard for the balance of the day, if you'd like to do
the honors...

**Comment by bollwyvl** [comment]
Here goes nothing!

**Pull request merged**
