### PR TITLE
[wip] add missing 0.7.0 builds by uncommenting

### PR DESCRIPTION
**Pull request by bollwyvl**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

This is the "hacky" approach to getting the remaining 0.7.0 builds out, missed by #15.

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
@bollwyvl Why is this working now?

**Comment by bollwyvl** [comment]
Poor explanation above: the multiple outputs don't respect some selectors,
and it really wants to test on py38. after the first PR goes through,
dagster exists for py38 so it can solve.

**Comment by bollwyvl** [comment]
Closed in favor of #18

**Pull request closed without merging**
