### PR TITLE
Unpin `sqlqlchemy`

### PR DESCRIPTION
**Pull request by dhirschfeld**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dhirschfeld** [comment]
@conda-forge-admin, please rerender

**Comment by dhirschfeld** [comment]
It looks like this hasn't been required since 1.3.8
https://github.com/dagster-io/dagster/pull/14618

**Comment by dhirschfeld** [comment]
https://github.com/dagster-io/dagster/blob/1.5.3/python_modules/dagster/setup.py#L76-L111

**Comment by dhirschfeld** [comment]
Ping @conda-forge/dagster - this should be good to merge. 

I changed to `update-grayskull` in the hope that it could automatically pick up these changes in future. If that's controversial I'm happy to revert.

**Comment by bollwyvl** [comment]
Greyskull is great and all, but this feedstock is... a lot to even update
the tarballs correctly, as new packages are created or renamed. Please
remove the update... Could try the hint-all tool, perhaps.

**Comment by bollwyvl** [comment]
Oh we had `hint-all`. Yeah, please roll back the `update-all`.

**Comment by dhirschfeld** [comment]
> Oh we had `hint-all`. Yeah, please roll back the `update-all`.

Done! The commits can be squashed to not create a mess.

**Comment by bollwyvl** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
